DROP DATABASE IF EXISTS combobox_dependientes;
CREATE DATABASE combobox_dependientes DEFAULT CHARACTER SET latin1 COLLATE latin1_bin;
USE combobox_dependientes;

CREATE TABLE pais (
	idpais 		INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	pais 		VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY USING BTREE (idpais)
) ENGINE=MyISAM;

CREATE TABLE estado (
	idestado 	INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	estado 		VARCHAR(50) DEFAULT NULL,
	pais 		INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY USING BTREE (idestado)
) ENGINE=MyISAM;

CREATE TABLE ciudad (
	idciudad 	INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ciudad 		VARCHAR(50) NOT NULL DEFAULT '',
	estado 		INT(11) NOT NULL DEFAULT '0',
	pais 		INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY USING BTREE (idciudad)
) ENGINE=MyISAM;